/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.ImageIcon;
import javax.swing.BorderFactory;
import java.awt.*;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.MySQL2;
import java.sql.Time;
import model.Session;

/**
 *
 * @author hasit
 */
public class Orders extends javax.swing.JPanel {

    public Orders() {
        initComponents();
        loadTable1();
    }

    public static int employee_id = Session.employeeId;

    private void loadTable1() {
        try {
            ResultSet resultset = MySQL2.executeSearch(
                    "SELECT "
                    + "CONCAT('INV', LPAD(CAST(i.id AS CHAR), 5, '0')) AS id, "
                    + "CONCAT('EMP', LPAD(CAST(e.id AS CHAR), 5, '0')) AS employee_idc, e.first_name, e.last_name, "
                    + "i.date AS date, "
                    + "i.payment AS value "
                    + "FROM invoice i "
                    + "INNER JOIN employee e ON e.id = i.employee_id "
                    + "ORDER BY date DESC"
            );

            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            while (resultset.next()) {
                Vector<String> vector = new Vector<>();

                vector.add(resultset.getString("id"));
                vector.add(resultset.getString("employee_idc"));
                vector.add(resultset.getString("first_name") + " " + resultset.getString("last_name"));
                vector.add(resultset.getString("date"));
                vector.add("Rs. " + resultset.getString("value"));

                model.addRow(vector);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated
// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel13 = new RoundedPanel(15, new Color(230, 230, 230), new Color(0,0,0,0));
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(650, 400));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setMaximumSize(new java.awt.Dimension(70000, 2147483647));
        jPanel6.setName(""); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 650));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel4.setMaximumSize(new java.awt.Dimension(65534, 70));
        jPanel4.setPreferredSize(new java.awt.Dimension(179, 70));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel7.setText("Orders");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 334, 50));

        jPanel1.add(jPanel4);

        jPanel6.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel13.setPreferredSize(new java.awt.Dimension(350, 848));
        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel13.add(jLabel5);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Transction ID", "Employee ID", "Employee Name", "Date", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(120, 120));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(1);
        }
        jTable1.setShowGrid(false);
        //jScrollPane1.setViewportView(jTable1);
        //jScrollPane1.setBorder(BorderFactory.createMatteBorder(1, 0, 1, 0, Color.BLACK));

        jTable1.setIntercellSpacing(new Dimension(0, 0));

        jTable1.setBackground(new Color(230, 230, 230));
        jTable1.setForeground(Color.BLACK);
        jTable1.setFont(new Font("Poppins", Font.PLAIN, 14));
        jTable1.setRowHeight(25);

        JTableHeader header = jTable1.getTableHeader();
        header.setBackground(new Color(230, 230, 230));
        header.setForeground(Color.BLACK);
        header.setFont(new Font("Poppins", Font.PLAIN, 14));
        header.setBorder(BorderFactory.createEmptyBorder());
        header.setOpaque(true);

        jPanel13.add(jScrollPane1);

        jPanel2.add(jPanel13, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel6);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
