/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.MySQL2;


/**
 *
 * @author hasit
 */
public class reciptionDashbord extends javax.swing.JPanel {
    
    


    private static reciptionDashbord dpba;
    public reciptionDashbord() {
        initComponents();
        loadDashboardData();
    }
    
    public static synchronized reciptionDashbord getInstance(){
        if(dpba==null){
            dpba=new reciptionDashbord();
        
        }
        return dpba;
    }

    private void loadDashboardData() {
    try {
        // Load Active Customers Count
        ResultSet activeCustomersRS = MySQL2.executeSearch("SELECT COUNT(*) as count FROM `customer` WHERE DATE(registered_date) = CURDATE()");
        if (activeCustomersRS.next()) {
            ActiveCustomersTotalNoLabel.setText(activeCustomersRS.getString("count"));
        } else {
            ActiveCustomersTotalNoLabel.setText("0");
        }
        
        // Load Complete Orders Count
      ResultSet rs = MySQL2.executeSearch(
    "SELECT COUNT(*) AS count FROM employee e " +
    "LEFT JOIN employee_attendance ea ON e.id = ea.employee_id AND ea.date = CURRENT_DATE " +
    "WHERE ea.id IS NULL");

if (rs.next()) {
    TotalOrdersTotalNoLabel.setText(rs.getString("count"));
} else {
    TotalOrdersTotalNoLabel.setText("0");
}

        
        // Load Failed Orders Count
        ResultSet failedOrdersRS = MySQL2.executeSearch(
            "SELECT COUNT(*) as count FROM `employee_attendance` WHERE `date` = CURRENT_DATE");
        if (failedOrdersRS.next()) {
            FailedOrdersTotalNoLabel.setText(failedOrdersRS.getString("count"));
        } else {
            FailedOrdersTotalNoLabel.setText("0");
        }
        
      
       
        
       
        
        // Load Progress Table
        loadProgressTable();
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}


private void loadProgressTable() {
    try {
        // Fetch lists
List<String> customers = getSingleColumnList("SELECT CONCAT(first_name, ' ', last_name) FROM customer WHERE DATE(registered_date) = CURDATE()");
        List<String> presentEmployees = getSingleColumnList("SELECT CONCAT(first_name, ' ', last_name) FROM employee WHERE id IN (SELECT DISTINCT employee_id FROM employee_attendance WHERE date = CURDATE())");
        List<String> absentEmployees = getSingleColumnList("SELECT CONCAT(first_name, ' ', last_name) FROM employee WHERE id NOT IN (SELECT DISTINCT employee_id FROM employee_attendance WHERE date = CURDATE())");
        List<String> foods = getSingleColumnList("SELECT title FROM product");

        // Determine max rows
        int max = Math.max(Math.max(customers.size(), presentEmployees.size()), Math.max(absentEmployees.size(), foods.size()));

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        // Build rows
        for (int i = 0; i < max; i++) {
            Vector<String> row = new Vector<>();
            row.add(i < customers.size() ? customers.get(i) : "");
            row.add(i < presentEmployees.size() ? presentEmployees.get(i) : "");
            row.add(i < absentEmployees.size() ? absentEmployees.get(i) : "");
            row.add(i < foods.size() ? foods.get(i) : "");
            model.addRow(row);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error loading progress data: " + e.getMessage());
    }
}



    


    
    
    

    
    // This method should be called when you want to refresh the dashboard data
    public void refreshDashboard() {
        loadDashboardData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // Your generated code here - DO NOT MODIFY
    // </editor-fold>
    private List<String> getSingleColumnList(String query) throws Exception {
    List<String> list = new ArrayList<>();
    try {
        ResultSet rs = MySQL2.executeSearch(query);
        while (rs.next()) {
            list.add(rs.getString(1)); // Get the first column value
        }
        rs.close();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "SQL Error: " + e.getMessage());
    }
    return list;
}


    // Variables declaration - do not modify                     
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new RoundedPanel(15, new Color(230, 230, 230), new Color(0,0,0,0));
        ActiveCustomersPanel = new RoundedPanel(15, new Color(230, 230, 230), new Color(0,0,0,0));
        ActiveCustomersLabel = new javax.swing.JLabel();
        ActiveCustomersTotalNoLabel = new javax.swing.JLabel();
        jPanel4 = new RoundedPanel(15, new Color(230, 230, 230), new Color(0,0,0,0));
        CompleteOrdersPanel = new RoundedPanel(15, new Color(230, 230, 230), new Color(0,0,0,0));
        CompleteOrdersLabel = new javax.swing.JLabel();
        TotalOrdersTotalNoLabel = new javax.swing.JLabel();
        jPanel3 = new RoundedPanel(15, new Color(230, 230, 230), new Color(0,0,0,0));
        FailedOrdersPanel = new RoundedPanel(15, new Color(230, 230, 230), new Color(0,0,0,0));
        FailedOrdersLabel = new javax.swing.JLabel();
        FailedOrdersTotalNoLabel = new javax.swing.JLabel();
        ProgressPanel = new RoundedPanel(15, new Color(230, 230, 230), new Color(0,0,0,0));
        ProgressLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(180, 188));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(20, 362));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel7, java.awt.BorderLayout.LINE_END);

        jPanel8.setPreferredSize(new java.awt.Dimension(20, 362));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel8, java.awt.BorderLayout.LINE_START);

        jPanel9.setPreferredSize(new java.awt.Dimension(1080, 20));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        jPanel10.setPreferredSize(new java.awt.Dimension(1080, 20));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel10, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout(0, 20));

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 120));
        jPanel1.setLayout(new java.awt.GridLayout(1, 6, 20, 0));

        jPanel6.setLayout(new java.awt.BorderLayout());

        ActiveCustomersPanel.setLayout(new java.awt.BorderLayout());

        ActiveCustomersLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        ActiveCustomersLabel.setForeground(new java.awt.Color(153, 0, 0));
        ActiveCustomersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ActiveCustomersLabel.setText("New Customers");
        ActiveCustomersLabel.setMaximumSize(new java.awt.Dimension(132, 50));
        ActiveCustomersLabel.setPreferredSize(new java.awt.Dimension(132, 50));
        ActiveCustomersPanel.add(ActiveCustomersLabel, java.awt.BorderLayout.PAGE_START);

        ActiveCustomersTotalNoLabel.setFont(new java.awt.Font("Poppins", 1, 60)); // NOI18N
        ActiveCustomersTotalNoLabel.setForeground(new java.awt.Color(0, 0, 1));
        ActiveCustomersTotalNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ActiveCustomersTotalNoLabel.setText("100");
        ActiveCustomersPanel.add(ActiveCustomersTotalNoLabel, java.awt.BorderLayout.CENTER);

        jPanel6.add(ActiveCustomersPanel, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel4.setLayout(new java.awt.BorderLayout());

        CompleteOrdersPanel.setLayout(new java.awt.BorderLayout());

        CompleteOrdersLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        CompleteOrdersLabel.setForeground(new java.awt.Color(153, 0, 51));
        CompleteOrdersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CompleteOrdersLabel.setText("Today Absent Employees");
        CompleteOrdersLabel.setMaximumSize(new java.awt.Dimension(214, 100));
        CompleteOrdersLabel.setPreferredSize(new java.awt.Dimension(214, 50));
        CompleteOrdersPanel.add(CompleteOrdersLabel, java.awt.BorderLayout.PAGE_START);

        TotalOrdersTotalNoLabel.setFont(new java.awt.Font("Poppins", 1, 60)); // NOI18N
        TotalOrdersTotalNoLabel.setForeground(new java.awt.Color(0, 0, 1));
        TotalOrdersTotalNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TotalOrdersTotalNoLabel.setText("100");
        CompleteOrdersPanel.add(TotalOrdersTotalNoLabel, java.awt.BorderLayout.CENTER);

        jPanel4.add(CompleteOrdersPanel, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel3.setLayout(new java.awt.BorderLayout());

        FailedOrdersPanel.setLayout(new java.awt.BorderLayout());

        FailedOrdersLabel.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        FailedOrdersLabel.setForeground(new java.awt.Color(153, 0, 51));
        FailedOrdersLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FailedOrdersLabel.setText("Today Present Employees");
        FailedOrdersLabel.setMaximumSize(new java.awt.Dimension(218, 50));
        FailedOrdersLabel.setPreferredSize(new java.awt.Dimension(218, 50));
        FailedOrdersPanel.add(FailedOrdersLabel, java.awt.BorderLayout.PAGE_START);

        FailedOrdersTotalNoLabel.setFont(new java.awt.Font("Poppins", 1, 60)); // NOI18N
        FailedOrdersTotalNoLabel.setForeground(new java.awt.Color(0, 0, 1));
        FailedOrdersTotalNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FailedOrdersTotalNoLabel.setText("100");
        FailedOrdersPanel.add(FailedOrdersTotalNoLabel, java.awt.BorderLayout.CENTER);

        jPanel3.add(FailedOrdersPanel, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        ProgressPanel.setLayout(new java.awt.BorderLayout());

        ProgressLabel.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        ProgressLabel.setForeground(new java.awt.Color(0, 0, 1));
        ProgressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProgressLabel.setText("Progress");
        ProgressPanel.add(ProgressLabel, java.awt.BorderLayout.PAGE_START);

        jTable1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "New Customer", "Today present employee", "Today absent Employee", "Foods"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.setShowGrid(false);
        jTable1.setIntercellSpacing(new Dimension(0, 0));

        jTable1.setBackground(new Color(230, 230, 230));
        jTable1.setForeground(Color.BLACK);
        jTable1.setFont(new Font("Poppins", Font.PLAIN, 14));
        jTable1.setRowHeight(25);

        JTableHeader header = jTable1.getTableHeader();
        header.setBackground(new Color(230, 230, 230));
        header.setForeground(Color.BLACK);
        header.setFont(new Font("Poppins", Font.PLAIN, 14));
        header.setBorder(BorderFactory.createEmptyBorder());
        header.setOpaque(true);

        ProgressPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(ProgressPanel, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActiveCustomersLabel;
    private javax.swing.JPanel ActiveCustomersPanel;
    private javax.swing.JLabel ActiveCustomersTotalNoLabel;
    private javax.swing.JLabel CompleteOrdersLabel;
    private javax.swing.JPanel CompleteOrdersPanel;
    private javax.swing.JLabel FailedOrdersLabel;
    private javax.swing.JPanel FailedOrdersPanel;
    private javax.swing.JLabel FailedOrdersTotalNoLabel;
    private javax.swing.JLabel ProgressLabel;
    private javax.swing.JPanel ProgressPanel;
    private javax.swing.JLabel TotalOrdersTotalNoLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    
}
