/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import model.MySQL2;

public class RequestDetailsDialog extends javax.swing.JDialog {

    private String requestId;
    private String currentStatus;
    
    
    public RequestDetailsDialog(java.awt.Frame parent, boolean modal, String requestId) {
        super(parent, modal);
        this.requestId = requestId;
        initComponents();
        setLocationRelativeTo(parent);
        loadRequestDetails();
    }
    
    private void loadRequestDetails() {
    try {
        String query = "SELECT er.*, CONCAT(e.first_name, ' ', e.last_name) AS employee_name, " +
                       "e.emp_id, e.mobile, e.email " +
                       "FROM employee_requests er " +
                       "INNER JOIN employee e ON er.employee_id = e.id " +
                       "WHERE er.request_id = '" + requestId + "'";
        
        System.out.println("Executing query: " + query); // Debug line
        
        ResultSet rs = MySQL2.executeSearch(query);
        
        if (rs.next()) {
            // Debug: Print all available columns
            System.out.println("Found request data:");
            System.out.println("Employee Name: " + rs.getString("employee_name"));
            System.out.println("Request ID: " + rs.getString("request_id"));
            System.out.println("Request Type: " + rs.getString("request_type"));
            
            // Set the form fields using your component names - with null checks
            String employeeName = rs.getString("employee_name");
            EmployeeNameLoading.setText(employeeName != null ? employeeName : "N/A");
            
            String requestIdFromDB = rs.getString("request_id");
            RequestIdLoading.setText(requestIdFromDB != null ? requestIdFromDB : "N/A");
            
            String empId = rs.getString("emp_id");
            EmployeeIDLoading.setText(empId != null ? empId : "N/A");
            
            String requestType = rs.getString("request_type");
            RequestTypeLoading.setText(requestType != null ? requestType : "N/A");
            
            String dateSubmitted = rs.getString("date_submitted");
            DateSubmittedLoading.setText(dateSubmitted != null ? dateSubmitted : "N/A");
            
            currentStatus = rs.getString("status");
            CurrentStatusLoading.setText(currentStatus != null ? currentStatus : "Pending");
            
            // Set request details in the text field
            String description = rs.getString("description");
            RequestDetailsLoading.setText(description != null ? description : "");
            
            // Enable/disable buttons based on current status
            if (currentStatus != null && (currentStatus.equals("Approved") || currentStatus.equals("Rejected"))) {
                ApproveButton.setEnabled(false);
                RejectButton.setEnabled(false);
                RequestDetailsLoading.setEditable(false);
            }
        } else {
            System.out.println("No request found with ID: " + requestId);
            JOptionPane.showMessageDialog(this, 
                "No request found with ID: " + requestId + "\n" +
                "Make sure the employee_requests table exists and has sample data.",
                "Request Not Found", 
                JOptionPane.WARNING_MESSAGE);
        }
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Error loading request details: " + e.getMessage() + "\n" +
            "This might be because the employee_requests table doesn't exist yet.\n" +
            "Please create the table and add sample data first.",
            "Database Error", 
            JOptionPane.ERROR_MESSAGE);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EmployeeNameLoading = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EmployeeIDLoading = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RequestIdLoading = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RequestTypeLoading = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DateSubmittedLoading = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CurrentStatusLoading = new javax.swing.JLabel();
        RequestDetailsLoading = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ApproveButton = new javax.swing.JButton();
        RejectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Employee Name");

        EmployeeNameLoading.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmployeeNameLoading.setText("EN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Employee ID");

        EmployeeIDLoading.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmployeeIDLoading.setText("EID");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Request ID");

        RequestIdLoading.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RequestIdLoading.setText("RID");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Request Type");

        RequestTypeLoading.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RequestTypeLoading.setText("RT");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Date Submitted");

        DateSubmittedLoading.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DateSubmittedLoading.setText("DS");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Current Status");

        CurrentStatusLoading.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CurrentStatusLoading.setText("CS");

        RequestDetailsLoading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestDetailsLoadingActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Request Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmployeeIDLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                    .addComponent(EmployeeNameLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(RequestIdLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RequestTypeLoading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateSubmittedLoading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CurrentStatusLoading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(RequestDetailsLoading)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RequestIdLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeNameLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmployeeIDLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RequestTypeLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateSubmittedLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CurrentStatusLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RequestDetailsLoading, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        ApproveButton.setText("APPROVE");
        ApproveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveButtonActionPerformed(evt);
            }
        });

        RejectButton.setText("REJECT");
        RejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ApproveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApproveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RejectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RequestDetailsLoadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestDetailsLoadingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RequestDetailsLoadingActionPerformed

    private void RejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RejectButtonActionPerformed
        updateRequestStatus("Rejected");
    }//GEN-LAST:event_RejectButtonActionPerformed

    private void ApproveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveButtonActionPerformed
      updateRequestStatus("Approved");
    }//GEN-LAST:event_ApproveButtonActionPerformed

    private void updateRequestStatus(String status) {
    String adminResponse = RequestDetailsLoading.getText().trim();
    
    if (adminResponse.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Please provide details/reason before " + status.toLowerCase() + " the request.",
            "Response Required", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    try {
        // Update the request status in database
        String updateQuery = "UPDATE employee_requests SET " +
                            "status = '" + status + "', " +
                            "admin_response = '" + adminResponse + "', " +
                            "response_date = NOW(), " +
                            "admin_id = 1 " +  // You might want to get the actual admin ID
                            "WHERE request_id = '" + requestId + "'";
        
        MySQL2.executeIUD(updateQuery);
        
        JOptionPane.showMessageDialog(this, 
            "Request has been " + status.toLowerCase() + " successfully!",
            "Success", 
            JOptionPane.INFORMATION_MESSAGE);
        
        // Update UI
        CurrentStatusLoading.setText(status);
        ApproveButton.setEnabled(false);
        RejectButton.setEnabled(false);
        RequestDetailsLoading.setEditable(false);
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Error updating request: " + e.getMessage(),
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
}

    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(RequestDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(RequestDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(RequestDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(RequestDetailsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            RequestDetailsDialog dialog = new RequestDetailsDialog(new javax.swing.JFrame(), true, "REQ001");
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ApproveButton;
    private javax.swing.JLabel CurrentStatusLoading;
    private javax.swing.JLabel DateSubmittedLoading;
    private javax.swing.JLabel EmployeeIDLoading;
    private javax.swing.JLabel EmployeeNameLoading;
    private javax.swing.JButton RejectButton;
    private javax.swing.JTextField RequestDetailsLoading;
    private javax.swing.JLabel RequestIdLoading;
    private javax.swing.JLabel RequestTypeLoading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
