/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import callbacks.SelectionListener;
import model.MySQL2;

/**
 *
 * @author Oshadha Bhanu
 */
public class StockManagementGRN extends javax.swing.JPanel {

        // ⚠️Whutto, Bota ona pamkak me pahala thiyena variable ekata koraam.⚠️
        int employeeID = 1; // ⬅️ employee id eka kohomahari me variable ekata load karaam. SQL query wenas
                            // koranda yannepa. query wenas korala kela unoth api na.

        /**
         * Creates new form StockManagementGRN
         */
        public StockManagementGRN() {
                initComponents();

        }

        private void loadGRNTable(){
                DefaultTableModel model = (DefaultTableModel) grnTable.getModel();
                model.setRowCount(0);

                String query = "SELECT g.grn_id, gi.price, g.paid_amount, g.date, br.branch_id, em.emp_id, sp.supplier_id " +
                "FROM "
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                selectStockProduct = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                quantity = new javax.swing.JTextField();
                jLabel2 = new javax.swing.JLabel();
                price = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                paidAmount = new javax.swing.JTextField();
                selectedStockProduct = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                selectedStockProductID = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                ResetFields = new javax.swing.JButton();
                searchBar = new javax.swing.JTextField();
                resetSearch = new javax.swing.JButton();
                selectedSupplierName = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                selectSupplier = new javax.swing.JButton();
                selectedSupplierID = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                createGRN = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                grnTable = new javax.swing.JTable();

                jPanel1.setBackground(new java.awt.Color(0, 0, 0));
                jPanel1.setForeground(new java.awt.Color(255, 255, 255));

                selectStockProduct.setBackground(new java.awt.Color(0, 153, 51));
                selectStockProduct.setForeground(new java.awt.Color(255, 255, 255));
                selectStockProduct.setText("Select Stock Product");
                selectStockProduct.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                selectStockProductActionPerformed(evt);
                        }
                });

                jLabel1.setText("Quantity");

                quantity.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                quantityActionPerformed(evt);
                        }
                });

                jLabel2.setText("Price");

                price.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                priceActionPerformed(evt);
                        }
                });

                jLabel3.setText("Paid Amount");

                paidAmount.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                paidAmountActionPerformed(evt);
                        }
                });

                selectedStockProduct.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                selectedStockProductActionPerformed(evt);
                        }
                });

                jLabel4.setText("Stock Product");

                selectedStockProductID.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                selectedStockProductIDActionPerformed(evt);
                        }
                });

                jLabel5.setText("Stock Product ID");

                ResetFields.setBackground(new java.awt.Color(204, 0, 0));
                ResetFields.setForeground(new java.awt.Color(255, 255, 255));
                ResetFields.setText("Reset Fields");
                ResetFields.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                ResetFieldsActionPerformed(evt);
                        }
                });

                searchBar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchBarActionPerformed(evt);
                        }
                });

                resetSearch.setBackground(new java.awt.Color(204, 0, 0));
                resetSearch.setForeground(new java.awt.Color(255, 255, 255));
                resetSearch.setText("Reset");
                resetSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                resetSearchActionPerformed(evt);
                        }
                });

                selectedSupplierName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                selectedSupplierNameActionPerformed(evt);
                        }
                });

                jLabel6.setText("Supplier Name");

                selectSupplier.setBackground(new java.awt.Color(0, 0, 204));
                selectSupplier.setForeground(new java.awt.Color(255, 255, 255));
                selectSupplier.setText("Select Supplier");
                selectSupplier.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                selectSupplierActionPerformed(evt);
                        }
                });

                jLabel7.setText("Supplier ID");

                createGRN.setBackground(new java.awt.Color(102, 0, 204));
                createGRN.setForeground(new java.awt.Color(255, 255, 255));
                createGRN.setText("Create GRN");
                createGRN.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                createGRNActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                false)
                                                                                                                .addComponent(jLabel1)
                                                                                                                .addComponent(selectStockProduct,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                146,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(quantity))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(21, 21, 21)
                                                                                                                                .addComponent(jLabel2))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(jLabel4)))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(27, 27, 27)
                                                                                                                                .addComponent(jLabel3)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                548,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(selectedStockProduct,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                187,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(38, 38, 38)
                                                                                                                                .addComponent(jLabel5)
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addComponent(selectedStockProductID,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                112,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(67, 67, 67)
                                                                                                                                .addComponent(ResetFields,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                101,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(searchBar,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                319,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGap(182, 182,
                                                                                                                                                                182)
                                                                                                                                                .addComponent(price,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                80,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                .addComponent(paidAmount,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                80,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGap(76, 76, 76)
                                                                                                                                                .addComponent(createGRN,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                146,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addComponent(jLabel7)
                                                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                                                false)
                                                                                                                                                                                .addComponent(selectedSupplierID,
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                                .addComponent(selectedSupplierName,
                                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                102,
                                                                                                                                                                                                Short.MAX_VALUE)))
                                                                                                                                                .addGap(221, 421,
                                                                                                                                                                Short.MAX_VALUE))
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(jLabel6)
                                                                                                                                                .addGap(72, 72, 72)
                                                                                                                                                .addComponent(selectSupplier)
                                                                                                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(resetSearch)
                                                                .addGap(10, 10, 10)));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                                .createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(15, 15, 15)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(selectStockProduct,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                36,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(selectedStockProduct,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel4)
                                                                                                                .addComponent(selectedStockProductID,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel5)
                                                                                                                .addComponent(ResetFields))
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                .createSequentialGroup()
                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                .addGroup(jPanel1Layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                                .addComponent(jLabel1)
                                                                                                                                                .addComponent(jLabel2)
                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                .addComponent(jLabel6)))
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                jPanel1Layout.createSequentialGroup()
                                                                                                                                                .addGap(5, 5, 5)
                                                                                                                                                .addComponent(selectSupplier,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                29,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(quantity,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(price,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(paidAmount,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(selectedSupplierName,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(jLabel7)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addGroup(jPanel1Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(selectedSupplierID,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(createGRN,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                36,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(10, 10, 10)
                                                                                                .addComponent(searchBar,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(resetSearch)))
                                                                .addGap(23, 23, 23)));

                grnTable.setBackground(new java.awt.Color(0, 0, 0));
                grnTable.setForeground(new java.awt.Color(255, 255, 255));
                grnTable.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null, null }
                                },
                                new String[] {
                                                "GoodReceive ID", "Stock Product", "Price", "Paid Amount", "Date",
                                                "Branch", "Employee", "Supplier"
                                }));
                jScrollPane1.setViewportView(grnTable);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                438,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
        }// </editor-fold>//GEN-END:initComponents

        private void createGRNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createGRNActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_createGRNActionPerformed

        private void selectedStockProductActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectedStockProductActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_selectedStockProductActionPerformed

        private void ResetFieldsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ResetFieldsActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_ResetFieldsActionPerformed

        private void selectStockProductActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectStockProductActionPerformed
                StockManagementSelectStockProduct SMSSP = new StockManagementSelectStockProduct();
                SMSSP.setSelectionListener(new SelectionListener<model.SelectProduct>() {
                        @Override
                        public void onItemSelected(model.SelectProduct product) {
                                selectedStockProduct.setText(product.getName());
                                selectedStockProductID.setText(product.getId());
                        }

                });

                SMSSP.setVisible(true);

        }// GEN-LAST:event_selectStockProductActionPerformed

        private void selectedStockProductIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectedStockProductIDActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_selectedStockProductIDActionPerformed

        private void selectSupplierActionPerformed(java.awt.event.ActionEvent evt) {
                StockManagementSelectSupplier SMSS = new StockManagementSelectSupplier();

                // Set the callback to receive the selected supplier (model.SelectSupplier)
                SMSS.setSelectionListener(new SelectionListener<model.SelectSupplier>() {
                        @Override
                        public void onItemSelected(model.SelectSupplier supplier) {
                                selectedSupplierName.setText(supplier.getName());
                                selectedSupplierID.setText(supplier.getId());
                                // Optionally set other fields here
                                // selectedSupplierID.setText(supplier.getId());
                        }
                });

                SMSS.setVisible(true);
        }

        private void selectedSupplierActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectedSupplierActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_selectedSupplierActionPerformed

        private void paidAmountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_paidAmountActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_paidAmountActionPerformed

        private void priceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_priceActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_priceActionPerformed

        private void quantityActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_quantityActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_quantityActionPerformed

        private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchBarActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_searchBarActionPerformed

        private void resetSearchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_resetSearchActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_resetSearchActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton ResetFields;
        private javax.swing.JButton createGRN;
        private javax.swing.JTable grnTable;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField paidAmount;
        private javax.swing.JTextField price;
        private javax.swing.JTextField quantity;
        private javax.swing.JButton resetSearch;
        private javax.swing.JTextField searchBar;
        private javax.swing.JButton selectStockProduct;
        private javax.swing.JButton selectSupplier;
        private javax.swing.JTextField selectedStockProduct;
        private javax.swing.JTextField selectedStockProductID;
        private javax.swing.JTextField selectedSupplierID;
        private javax.swing.JTextField selectedSupplierName;
        // End of variables declaration//GEN-END:variables
}
